In [7]:
# set the absolute path where the KIT_4_ABM folder is located
global_path = 'C:/Users/nel_t/Documents/WORK/PROJECTS/a_KIT_4_ABM'   # <--- CHANGE THIS PATH to the one on your computer
code_path   = global_path + '/SRC'

# import the KIT_4_ABM package
import sys
sys.path.append(code_path)
import KIT_4_ABM as kit
import pprint

In [11]:
%%time
P_lay, P_dyn, P_sim, P_rec = kit.import_parameters("PAR_desired.json")
n_trials = 1
for i in range(n_trials):
    print(i)
    res = kit.run_sim(P_lay, P_dyn, P_sim, P_rec)
    kit.write_h5(i, P_rec, res)
data = kit.load_data_from_h5('SIRB_beta_0_02_01_h_0_betasymm_01.h5')
pprint.pprint(data)

0
{'Simulation_0': {'ALL-data': array([[1, 2, 1, 1],
       [1, 2, 1, 1],
       [1, 2, 1, 1],
       [1, 2, 1, 1],
       [1, 2, 1, 1],
       [1, 2, 2, 1],
       [1, 2, 2, 1],
       [1, 2, 2, 1],
       [1, 2, 2, 1],
       [1, 2, 2, 1],
       [1, 2, 2, 1]]),
                  'ALL-time': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, -1])}}
CPU times: total: 0 ns
Wall time: 15 ms


In [31]:
def print_h5_data(h5_filename):
    # Reading the HDF5 file
    with h5py.File(h5_filename, 'r') as hf:
        print("Data in the HDF5 file:")
        for simulation_name in hf.keys():
            simulation_group = hf[simulation_name]
            print(f"\nSimulation: {simulation_name}")
            for key in simulation_group.keys():
                data = simulation_group[key][()]
                if np.isscalar(data):
                    print(f"Scalar - {key}: {data}")
                elif isinstance(data, np.ndarray) and len(data.shape) == 1:
                    print(f"Array - {key}: {data}")
                elif isinstance(data, np.ndarray) and len(data.shape) > 1:
                    print(f"Matrix - {key}:")
                    print(data)


In [38]:
save_data_to_h5(res, "results.h5", 0)

ALL <Save_Functions.Saves object at 0x0000020A37C940D0>
data =  [[1 1 1 2]
 [1 1 1 2]
 [1 1 1 2]
 [1 2 1 3]
 [1 2 1 3]
 [1 2 1 3]
 [1 2 1 3]
 [1 2 1 3]
 [1 2 1 3]
 [1 2 1 3]
 [1 2 1 3]] 
time =  [ 0  1  2  3  4  5  6  7  8  9 -1]


In [5]:
print_h5_data('results.h5')

Data in the HDF5 file:

Simulation: Simulation_0


In [9]:
data = load_data_from_h5('SIRB_beta_0_02_01_h_0_betasymm_01.h5')

In [10]:
import pprint
pprint.pprint(data)

{'Simulation_0': {'ALL-data': array([[3, 1, 1, 1],
       [3, 1, 1, 1],
       [3, 1, 1, 1],
       [3, 1, 1, 1],
       [3, 1, 1, 1],
       [3, 1, 1, 1],
       [3, 1, 1, 1],
       [3, 1, 1, 1],
       [3, 1, 1, 1],
       [3, 1, 1, 1],
       [3, 1, 1, 1]]),
                  'ALL-time': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, -1])}}
