In [1]:
# set the absolute path where the KIT_4_ABM folder is located
global_path = 'C:/Users/nel_t/Documents/WORK/PROJECTS/KIT_4_ABM'   # <--- CHANGE THIS PATH to the one on your computer
code_path   = global_path + '/SRC'   # <--- CHANGE THIS PATH to the one on your computer

# import the KIT_4_ABM package
import sys
sys.path.append(code_path)
import KIT_4_ABM as kit

In [3]:
%%time
P_lay, P_dyn, P_sim, P_rec = kit.import_parameters("PAR_desired.json")
n_trials = 1
for i in range(n_trials):
    print(i)
    res = kit.run_sim(P_lay, P_dyn, P_sim, P_rec)
    #kit.write_h5(i, n_trials, P_rec, res)

print(res.R.data)
print(len(res.R.time))
print(res.R.time)

0


KeyError: 'DATA'

In [7]:
attrs = [a for a in dir(res) if not a.startswith('_')]
print(attrs)

['R']


In [20]:
# I want to convert an np.array "a" of dtype=object to a np.array "b" of dtype=float
import numpy as np
b = np.array(a, dtype=float)

In [3]:
# read the "SIRB_beta_0_02_01_h_0_betasymm_01.h5" file:

import h5py
import numpy as np
import matplotlib.pyplot as plt

filename = "SIRB_beta_0_02_01_h_0_betasymm_01.h5"
with h5py.File(filename, 'r') as file:
    # Define a function to print dataset names
    def print_dataset_names(name):
        if isinstance(file[name], h5py.Dataset):
            print(name)

    # Visit all items in the file to print dataset names
    file.visit(print_dataset_names)

{'N': 3, 'note': "the default is to save nothing, and the file name is 'none.txt' and it will be empty, default DT = 0, which means not to save anything runtime", 'filename': 'SIRB_beta_0_02_01_h_0_betasymm_01.txt', 'Recording_0': {'END': 'True', 'func': 'frac', 'target_fraction': 3, 'layer': 0, 'target': 'health_status', 'name': 'R', 'BEGIN': 'False', 'DT': 0, 'DATA': array([0.63], dtype=object), 'count': 1}, 'Recording_1': {'END': 'True', 'func': 'homophily', 'layer': 0, 'target': 'behavior_status', 'name': 'H', 'BEGIN': 'False', 'DT': 0, 'DATA': array([0.005136907141887859], dtype=object), 'count': 1}, 'Recording_2': {'END': 'True', 'func': 'variance', 'layer': 0, 'target': 'behavior_status', 'name': 'V', 'BEGIN': 'False', 'DT': 0, 'DATA': array([0.212297541527367], dtype=object), 'count': 1}}


In [4]:
with h5py.File(filename, 'r') as file:
    # print all the names of the datasets in the file
    print(list(file.keys()))

[]


In [6]:
Data.R_t

array([inf])

In [1]:
import h5py

file_path = "SIRB_beta_0_02_01_h_0_betasymm_01.h5"  # Replace with the path to your HDF5 file
with h5py.File(file_path, 'r') as file:
    # List all the top-level groups or datasets in the file
    print("Top-level items in the HDF5 file:")
    for item_name in file:
        print(item_name)

    # You can also inspect the type and shape of datasets if they exist
    dataset_name = 'dataset_name'  # Replace with the actual dataset name
    if dataset_name in file:
        dataset = file[dataset_name]
        print(f"Dataset '{dataset_name}' information:")
        print(f"Shape: {dataset.shape}")
        print(f"Data type: {dataset.dtype}")

    # You can also inspect attributes of datasets or groups
    group_name = 'group_name'  # Replace with the actual group name
    if group_name in file:
        group = file[group_name]
        print(f"Attributes of group '{group_name}':")
        for attr_name, attr_value in group.attrs.items():
            print(f"{attr_name}: {attr_value}")

Top-level items in the HDF5 file:


In [2]:
import numpy as np

N = 5  # Number of elements in the outer array
L = 3  # Length of each inner array

# Create an empty array to hold the result
result = np.empty(N, dtype=object)

# Fill the array with arrays of length L
for i in range(N):
    result[i] = np.random.rand(L)  # You can use np.zeros(L) or any other array creation method here

print(result)

[array([0.99383692, 0.86884735, 0.3068987 ])
 array([0.26168801, 0.87079567, 0.29780181])
 array([0.8671568 , 0.33569018, 0.27408986])
 array([0.77231458, 0.6344441 , 0.36432713])
 array([0.3681716 , 0.78590602, 0.81312859])]


In [3]:
type(result)

numpy.ndarray

In [4]:
a = np.empty(N, dtype=object)

In [6]:
a[0] = np.array([1,2,3])

In [8]:
type(a)

numpy.ndarray